name: Build Experiment Container

on:
  # Always test on pull request
  pull_request: []

  # Deploy on merge to main
  push:
    branches:
      - main

jobs:
  deploy-test-containers:
    runs-on: ubuntu-latest
    name: Build Container
    steps:
      - name: Checkout
        uses: actions/checkout@v2        

      - name: Build Experiment Factory Container
        env:
          dirname: ${{ github.event.repository.name }}
        run: |
          # Move one directory up
          cd ../         
          docker run -v $PWD:/data quay.io/vanessa/expfactory-builder build /data/${dirname}
          printf "Files generated are:\n"
          ls
          docker build -t ghcr.io/expfactory-experiments/${dirname} .
          docker tag ghcr.io/expfactory-experiments/${dirname}:latest ghcr.io/expfactory-experiments/${dirname}:${GITHUB_SHA::8} 
          docker images | grep expfactory

      - name: Login and Deploy Test Container
        if: (github.event_name != 'pull_request')
        env:
          dirname: ${{ github.event.repository.name }}
        run: |
            docker images
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
            docker push ghcr.io/expfactory-experiments/${dirname}
            docker push ghcr.io/expfactory-experiments/${GITHUB_SHA::8}
